#!/bin/sh
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --no--fehbg --randomize ~/Templates/* &
pidof -q picom || { picom --config "$HOME"/.config/picom/picom.conf & }
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap         18

bspc config normal_border_color "#dc1b1b"
bspc config focused_border_color "#dc1b1b"
bspc config urgent_border_color "#dc1b1b"
bspc config presel_border_color "#dc1b1b"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer   true
 e
# Reglas para ventana especificas
# bspc rule -a Test state=floating

# para arreglar el tamaño de las aplicaciones java
wmname LG3D

